package com.delivery.sopo.enums

enum class NavigatorEnum
{
    REGISTER_INPUT,
    REGISTER_INPUT_REVISE,
    REGISTER_INPUT_INIT,
    REGISTER_INPUT_SUCCESS,
    REGISTER_SELECT,
    REGISTER_CONFIRM,

    UPDATE_NICKNAME,

    INQUIRY_PARCEL,
    DETAIL_PARCEL,
    DELETE_PARCEL,

    MAIN
}