package com.delivery.sopo.enums

enum class ResponseCode(val CODE: String, val MSG: String, val HTTP_STATUS: Int) {
    SUCCESS("0000", "SUCCESS", 200),
    ALREADY_LOGGED_IN("0010", "다른 디바이스에 로그인되어있습니다.\n계속 진행을 할까요?", 200),
    VALIDATION_ERROR("VA01","지원하지 않는 택배사입니다.\n다시 한번 확인해주세요.", 400),
    KAKAO_SIMPLE_FAIL("KA00", "Fail to join by kakao", 400),
    KAKAO_SIMPLE_ALREADY_USE_EMAIL("KA01", "Already use that email", 400),
    KAKAO_SIMPLE_NOT_VERIFYED_USER("KA02", "Can not verify kakao user", 400),
    KAKAO_SIMPLE_CORRUPT_EMAIL("KA03", "kakao account`s email is not matched with given email", 400),
    KAKAO_SIMPLE_FAIL_TO_PASING_DATA("KA04", "Fail to parse the kakao data", 400),
    KAKAO_SIMPLE_CORRUPT_EMAIL2("KA05", "After verify kakao user, doesn`t match email(parameter != user data)", 400),
    KAKAO_SIMPLE_CANNOT_FIND_FIREBASE_USER("KA06", "Can not find firebase user searched by email", 400),
    KAKAO_SIMPLE_FAIL_TO_UPDATE_AUTH_TOKEN("KA07", "Fail to update custom token", 400),
    FAIL_TO_FIND_API_ACCOUNT("AP01","Can`t find api account!", 400),
    FAIL_TO_FIND_SOPO_USER("AP02", "Can`t find Sopo User", 400),
    FAIL_TO_SAVE_API_ACCOUNT("AP03", "Fail to save Api account", 400),
    FAIL_TO_SAVE_SOPO_USER("AP04", "Fail to save Sopo User", 400),
    INVALID_USER("AP05", "Invalid user", 400),
    FAIL_TO_GET_USER_BY_FIREBASE_UID("AP06", "Fail to get user by firebase`s uid", 400),
    FAIL_TO_UPDATE_USER_DEVICE_INFO("AP07", "Fail to update user`s device-info", 400),
    FAIL_TO_REQUEST_FOR_UPDATING("UP01", "Fail to request for updating", 400),
    SEARCH_PARCEL_NULL_ERROR("PC01", "DeliveryTracking api`s result is null", 400),
    FAIL_TO_SAVE_PARCEL("PC02","fail to save client`s parcel", 400),
    FAIL_TO_SEARCH_PARCEL("PC03","fail to get client`s parcel [Delivery Api]", 400),
    CAN_NOT_FIND_PARCEL("PC04","Can`t find a parcel", 400),
    FAIL_TO_FIND_PARCEL("PC05","Fail to find a parcel", 400),
    FAIL_TO_DELETE_PARCEL("PC06","Fail to delete parcels", 400),
    FAIL_TO_UPDATE_USER_FIREBASE_TOKEN("US01","Fail to update user`s firebase token", 400),
    UNKNOWN_ERROR("9999", "UNKNOWN_ERROR", 400),
    UNAUTHORIZED_ACCESS_ERROR("BC01", "UNAUTHORIZED ACCESS", 401),
    NOT_FOUND_ERROR("BC02", "NOT FOUND", 403),
    FORBIDDEN_ACCESS_ERROR("BC03", "FORBIDDEN ACCESS", 404),
    JWT_INVALID_SIGNATURE("JW01", "Invalid JWT signature", 401),
    JWT_INVALID("JW99", "Invalid JWT token", 401),
    JWT_EXPIRED_TOKEN("JW02", "Expired JWT token", 401),
    JWT_UNSUPPORTED_TOKEN("JW03","Unsupported JWT token", 401),
    JWT_ILLEGALARGUMENT("JW04","JWT claims string is empty", 401)
}