package com.delivery.sopo.enums

// todo 한글 패치
enum class ResponseCode(val CODE: String, var MSG: String, val HTTP_STATUS: Int? = 0) {
    SUCCESS("0000", "SUCCESS", 200),
    ALREADY_LOGGED_IN("0010", "다른 디바이스에서 로그인 중 입니다. \n지금 디바이스에서 로그인하겠습니까?", 409),
    ALREADY_REGISTERED_USER("0011", "ALREADY_REGISTERED", 400),
    VALIDATION_ERROR("VA01","", 400),
    KAKAO_SIMPLE_FAIL("KA00", "Fail to join by kakao", 400),
    KAKAO_SIMPLE_ALREADY_USE_EMAIL("KA01", "Already use that email", 400),
    KAKAO_SIMPLE_NOT_VERIFYED_USER("KA02", "Can not verify kakao user", 400),
    KAKAO_SIMPLE_CORRUPT_EMAIL("KA03", "kakao account`s email is not matched with given email", 400),
    KAKAO_SIMPLE_FAIL_TO_PASING_DATA("KA04", "Fail to parse the kakao data", 400),
    KAKAO_SIMPLE_CORRUPT_EMAIL2("KA05", "After verify kakao user, doesn`t match email(parameter != user data)", 400),
    KAKAO_SIMPLE_CANNOT_FIND_FIREBASE_USER("KA06", "Can not find firebase user searched by email", 400),
    KAKAO_SIMPLE_FAIL_TO_UPDATE_AUTH_TOKEN("KA07", "Fail to update custom token", 400),
    FAIL_TO_FIND_API_ACCOUNT("AP01","Can`t find api account!", 400),
    FAIL_TO_FIND_SOPO_USER("AP02", "해당 고객님을 찾을 수가 없습니다.", 400),
    FAIL_TO_SAVE_API_ACCOUNT("AP03", "Fail to save Api account", 400),
    FAIL_TO_SAVE_SOPO_USER("AP04", "Fail to save Sopo User", 400),
    FAIL_TO_JOIN_SOPO_USER("AP04", "Fail to join..", 400),
    ALREADY_SIGN_OUT_USER("AP08", "Fail to join..", 400),
    INVALID_USER("AP05", "Invalid user", 400),
    FAIL_TO_GET_USER_BY_FIREBASE_UID("AP06", "Fail to get user by firebase`s uid", 400),
    FAIL_TO_UPDATE_USER_DEVICE_INFO("AP07", "Fail to update user`s device-info", 400),
    FAIL_TO_REQUEST_FOR_UPDATING("UP01", "Fail to request for updating", 400),
    SEARCH_PARCEL_NULL_ERROR("PC01", "DeliveryTracking api`s result is null", 400),
    FAIL_TO_SAVE_PARCEL("PC02","fail to save client`s parcel", 400),
    FAIL_TO_SEARCH_PARCEL("PC03","fail to get client`s parcel [Delivery Api]", 400),
    CAN_NOT_FIND_PARCEL("PC04","Can`t find a parcel", 400),
    FAIL_TO_FIND_PARCEL("PC05","Fail to find a parcel", 400),
    FAIL_TO_DELETE_PARCEL("PC06","Fail to delete parcels", 400),
    ALREADY_REGISTERED_PARCEL("PC07", "이미 등록된 택배입니다.\n확인 후 다시 시도해주세요.", 400),
    FAIL_TO_UPDATE_USER_FIREBASE_TOKEN("US01","Fail to update user`s firebase token", 400),
    UNKNOWN_ERROR("9999", "알 수 없는 에러입니다. 문의해주세요.", 400),
    UNAUTHORIZED_ACCESS_ERROR("BC01", "UNAUTHORIZED ACCESS",401),
    NOT_FOUND_ERROR("BC02", "NOT FOUND", 404),
    FORBIDDEN_ACCESS_ERROR("BC03", "FORBIDDEN ACCESS", 403),
    JWT_INVALID_SIGNATURE("JW01", "Invalid JWT signature",401),
    JWT_INVALID("JW99", "Invalid JWT token",401),
    JWT_EXPIRED_TOKEN("JW02", "Expired JWT token",401),
    JWT_UNSUPPORTED_TOKEN("JW03","Unsupported JWT token",401),
    JWT_ILLEGALARGUMENT("JW04","JWT claims string is empty",401),
    JWT_CAN_NOT_FIND_TOKEN("JW05", "Can not find the jwt Token", 400),

    TOKEN_ERROR_INVALID_CLIENT("TK01", "INVALID_CLIENT", 400),
    TOKEN_ERROR_UNAUTHORIZED_CLIENT("TK02", "UNAUTHORIZED_CLIENT", 400),
    TOKEN_ERROR_INVALID_GRANT("TK03", "INVALID_GRANT", 400),
    TOKEN_ERROR_INVALID_SCOPE("TK04", "INVALID_SCOPE", 400),
    TOKEN_ERROR_INVALID_TOKEN("TK05", "INVALID_TOKEN", 400),
    TOKEN_ERROR_REDIRECT_URI_MISMATCH("TK06", "REDIRECT_URI_MISMATCH", 400),
    TOKEN_ERROR_UNSUPPORTED_GRANT_TYPE("TK07", "UNSUPPORTED_GRANT_TYPE", 400),
    TOKEN_ERROR_UNSUPPORTED_RESPONSE_TYPE("TK08", "UNSUPPORTED_RESPONSE_TYPE", 400),
    TOKEN_ERROR_ACCESS_DENIED("TK09", "ACCESS_DENIED", 400),
    TOKEN_ERROR_INVALID_REQUEST("TK10", "INVALID_REQUEST", 400),
    TOKEN_ERROR_ALREADY_LOGGED_IN("TK11","ALREADY_LOGGED_IN" , 400),
    TOKEN_ERROR_DEVICE_INFO_IS_EMPTY("TK12", "DEVICE_INFO_IS_EMPTY", 400),
    TOKEN_ERROR_VALIDATION("TK13", "이메일 또는 비밀번호를 다시 확인해주세요.", 400),
    TOKEN_ERROR_UNKNOWN("TK99", "UNKNOWN_TOKEN_ERROR", 400),

    LOCAL_ERROR_TYPE_MISS("LC01", "Type Miss Match"),
    ERROR_RESPONSE_DATA_IS_NULL("ER01", "Response data가 없습니다."),

    ERROR_UNKNOWN("9999", "알수 없는 에러", 400);


}