package com.delivery.sopo.util.fun_util

import com.delivery.sopo.enums.ResponseCode.*

object CodeUtil
{
    fun returnCodeMsg(code: String?): String
    {
        return when (code)
        {
            SUCCESS.CODE -> SUCCESS.MSG
            ALREADY_LOGGED_IN.CODE -> ALREADY_LOGGED_IN.MSG
            VALIDATION_ERROR.CODE -> VALIDATION_ERROR.MSG
            KAKAO_SIMPLE_FAIL_TO_UPDATE_AUTH_TOKEN.CODE -> KAKAO_SIMPLE_FAIL_TO_UPDATE_AUTH_TOKEN.MSG
            KAKAO_SIMPLE_FAIL.CODE -> KAKAO_SIMPLE_FAIL.MSG
            INVALID_USER.CODE -> INVALID_USER.MSG
            FAIL_TO_GET_USER_BY_FIREBASE_UID.CODE -> FAIL_TO_GET_USER_BY_FIREBASE_UID.MSG
            KAKAO_SIMPLE_ALREADY_USE_EMAIL.CODE -> KAKAO_SIMPLE_ALREADY_USE_EMAIL.MSG
            KAKAO_SIMPLE_NOT_VERIFYED_USER.CODE -> KAKAO_SIMPLE_NOT_VERIFYED_USER.MSG
            FAIL_TO_UPDATE_USER_DEVICE_INFO.CODE -> FAIL_TO_UPDATE_USER_DEVICE_INFO.MSG
            KAKAO_SIMPLE_CORRUPT_EMAIL.CODE -> KAKAO_SIMPLE_CORRUPT_EMAIL.MSG
            KAKAO_SIMPLE_FAIL_TO_PASING_DATA.CODE -> KAKAO_SIMPLE_FAIL_TO_PASING_DATA.MSG
            KAKAO_SIMPLE_CORRUPT_EMAIL2.CODE -> KAKAO_SIMPLE_CORRUPT_EMAIL2.MSG
            KAKAO_SIMPLE_CANNOT_FIND_FIREBASE_USER.CODE -> KAKAO_SIMPLE_CANNOT_FIND_FIREBASE_USER.MSG
            FAIL_TO_FIND_API_ACCOUNT.CODE -> FAIL_TO_FIND_API_ACCOUNT.MSG
            FAIL_TO_FIND_SOPO_USER.CODE -> FAIL_TO_FIND_SOPO_USER.MSG
            FAIL_TO_SAVE_API_ACCOUNT.CODE -> FAIL_TO_SAVE_API_ACCOUNT.MSG
            FAIL_TO_SAVE_SOPO_USER.CODE -> FAIL_TO_SAVE_SOPO_USER.MSG
            FAIL_TO_REQUEST_FOR_UPDATING.CODE -> FAIL_TO_REQUEST_FOR_UPDATING.MSG
            SEARCH_PARCEL_NULL_ERROR.CODE -> SEARCH_PARCEL_NULL_ERROR.MSG
            FAIL_TO_SAVE_PARCEL.CODE -> FAIL_TO_SAVE_PARCEL.MSG
            FAIL_TO_SEARCH_PARCEL.CODE -> FAIL_TO_SEARCH_PARCEL.MSG
            CAN_NOT_FIND_PARCEL.CODE -> CAN_NOT_FIND_PARCEL.MSG
            FAIL_TO_FIND_PARCEL.CODE -> FAIL_TO_FIND_PARCEL.MSG
            FAIL_TO_DELETE_PARCEL.CODE -> FAIL_TO_DELETE_PARCEL.MSG
            ALREADY_REGISTERED_PARCEL.CODE -> ALREADY_REGISTERED_PARCEL.MSG
            FAIL_TO_UPDATE_USER_FIREBASE_TOKEN.CODE -> FAIL_TO_UPDATE_USER_FIREBASE_TOKEN.MSG
            UNKNOWN_ERROR.CODE -> UNKNOWN_ERROR.MSG
            UNAUTHORIZED_ACCESS_ERROR.CODE -> UNAUTHORIZED_ACCESS_ERROR.MSG
            NOT_FOUND_ERROR.CODE -> NOT_FOUND_ERROR.MSG
            FORBIDDEN_ACCESS_ERROR.CODE -> FORBIDDEN_ACCESS_ERROR.MSG
            JWT_INVALID_SIGNATURE.CODE -> JWT_INVALID_SIGNATURE.MSG
            JWT_INVALID.CODE -> JWT_INVALID.MSG
            JWT_EXPIRED_TOKEN.CODE -> JWT_EXPIRED_TOKEN.MSG
            JWT_UNSUPPORTED_TOKEN.CODE -> JWT_UNSUPPORTED_TOKEN.MSG
            JWT_ILLEGALARGUMENT.CODE -> JWT_ILLEGALARGUMENT.MSG
            else -> "알수 없는 오류입니다."
        }
    }
}